// Bazarish project (c) 2026
#pragma once

#include <bazarish/I2p.hpp>

#include <chrono>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

namespace bazarish::sam {

// Where i2pd listens unless its configuration says otherwise.
inline constexpr const char* kDefaultHost = "127.0.0.1";
inline constexpr std::uint16_t kDefaultControlPort = 7656;
inline constexpr std::uint16_t kDatagramPortBelowControl = 1;

struct RouterAddress {
    std::string host = kDefaultHost;
    std::uint16_t controlPort = kDefaultControlPort;
    // 0 selects i2pd's own default: one below the control port.
    std::uint16_t datagramPort = 0;

    std::uint16_t resolvedDatagramPort() const;
};

enum class Result {
    eOk,
    eInvalidId,
    eDuplicatedId,
    eInvalidKey,
    eCantReachPeer,
    eI2pError,
    eUnknown,
};

std::string_view toString(Result result);

class Error : public std::runtime_error {
public:
    Error(Result result, const std::string& message);
    Result result() const;

private:
    Result result_;
};

enum class Style { eStream, eDatagram, eRaw };

struct SessionConfig {
    // The private keys as I2P base64.
    std::string privateKeys;
    Style style = Style::eStream;
    i2p::Privacy privacy = i2p::Privacy::eMax;
    int tunnelQuantity = i2p::kDefaultTunnelQuantity;
    bool published = true;
};

// A destination generated by the router, both halves I2P base64.
struct Destination {
    std::string publicBase64;
    std::string privateBase64;
};

std::string probe(const RouterAddress& router);

Destination generateDestination(const RouterAddress& router);

using Socket = std::intptr_t;

class Stream {
public:
    explicit Stream(Socket socket);
    ~Stream();

    Stream(const Stream&) = delete;
    Stream& operator=(const Stream&) = delete;

    void setReadTimeout(int seconds);
    std::size_t readSome(void* buffer, std::size_t size);
    void readExact(void* buffer, std::size_t size);
    void writeAll(const void* data, std::size_t size);
    std::size_t pendingBytes() const;
    void close();

private:
    Socket socket_;
    int readTimeoutSeconds_ = 0;
};

class Session {
public:
    Session(RouterAddress router, SessionConfig config, std::chrono::seconds readyTimeout);
    ~Session();

    Session(const Session&) = delete;
    Session& operator=(const Session&) = delete;

    // Our own destination, base64 and as the ".b32.i2p" host peers dial.
    const std::string& publicDestination() const;
    const std::string& privateKeys() const;
    std::string routingHost() const;

    bool alive() const;

    // Opens a stream to a ".b32.i2p" host (b32 or b33) or a base64 destination.
    std::unique_ptr<Stream> connect(
        const std::string& destination, std::chrono::seconds timeout);

    void listen();
    // Waits for an incoming stream and fills peerDestination with the caller's base64 destination.
    std::unique_ptr<Stream> accept(
        std::string& peerDestination, std::chrono::milliseconds timeout);

    // One datagram to a host or base64 destination.
    void sendDatagram(const std::string& destination, const void* data, std::size_t size);
    std::vector<std::uint8_t> receiveDatagram(
        std::string* peerDestination, std::chrono::milliseconds timeout);

private:
    struct Impl;
    std::unique_ptr<Impl> impl_;
};

}  // namespace bazarish::sam
